// Generated by CodiumAI
import { describe, it, expect } from 'vitest'
import { useComputed } from '.'
import { ref } from 'vue'

// Generated by CodiumAI

describe('useComputed', () => {
  // Tests that the function 'useComputed' returns a computed ref when no source is provided
  it('should return a computed ref when no source is provided', () => {
    // Arrange
    const getter = () => 5

    // Act
    const result = useComputed(getter)

    // Assert
    expect(result.value).toBe(5)
  })

  // Tests that the function 'useComputed' returns a readonly computed ref when a source is provided and setter isn't
  it('should return a readonly computed ref when a source is provided and a setter is not', () => {
    // Arrange
    const count = ref(0)
    const getter = () => count.value * 2
    const source = [count]

    // Act
    const result = useComputed(getter, source)

    // Assert
    expect(result.value).toBe(0)
    result.value = 1
    expect(result.value).toBe(0)
  })

  // Tests that the function 'useComputed' computes the value correctly based on the provided function
  it('should compute and update the value correctly based on the provided function', () => {
    // Arrange
    const count = ref(1)
    const getter = () => count.value * 2
    const source = [count]

    // Act
    const result = useComputed(getter, source)

    // Assert
    expect(result.value).toBe(2)

    // Update source
    count.value = 2

    // Assert
    expect(result.value).toBe(4)
  })

  // Tests that the function 'useComputed' handles an empty source array
  it('should handle an empty source array', () => {
    // Arrange
    const getter = () => 1
    const source = [] as any

    // Act
    const result = useComputed(getter, source)

    // Assert
    expect(result.value).toBe(1)
  })
})
