// Generated by CodiumAI
import { useVueTable, getCoreRowModel, createColumnHelper } from './adapter'
// @ts-ignore-next-line
import { type Person, makeData } from './mockData'

const columnHelper = createColumnHelper<Person>()

const columns = [
  columnHelper.accessor('firstName', {
    cell: (info) => info.getValue(),
    footer: (props) => props.column.id,
  }),

  columnHelper.accessor('lastName', {
    id: 'lastName',
    header: () => 'Last Name',
    footer: (props) => props.column.id,
  }),

  columnHelper.accessor('age', {
    header: () => 'Age',
    footer: (props) => props.column.id,
  }),

  columnHelper.accessor('visits', {
    header: () => 'Visits',
    footer: (props) => props.column.id,
  }),

  columnHelper.accessor('status', {
    header: 'Status',
    footer: (props) => props.column.id,
  }),

  columnHelper.accessor('progress', {
    header: 'Profile Progress',
    footer: (props) => props.column.id,
  }),
]

function makeTable(data: Person[]) {
  return useVueTable({
    data,
    columns,
    getCoreRowModel: getCoreRowModel(),
  })
}

//----------------------------------------------------------------------------------------------------
// 📌 tests
//----------------------------------------------------------------------------------------------------

describe('useVueTable', () => {
  // Tests that the function creates a table with default options when no options are provided
  it('should create a table with default options when no options are provided', () => {
    // use fakerjs to mock data
    const options = [] as Person[]
    const table = makeTable(options)

    // assert that the table is created with default options
    expect(table).toBeDefined()
    expect(table.options).toMatchObject({
      state: {},
      onStateChange: expect.any(Function),
      renderFallbackValue: null,
      mergeOptions: expect.any(Function),
    })
  })

  // Tests that the function creates a table with provided options
  it('should create a table with provided options', () => {
    // use fakerjs to mock data
    const options = makeData(2)
    const table = makeTable(options)

    // assert that the table is created with provided options
    expect(table).toBeDefined()
    expect(table.options).toMatchObject(options)
  })

  //   // Tests that the function merges default and provided options
  //   it('should merge default and provided options', () => {
  //     // use fakerjs to mock data
  //     const defaultOptions = {
  //       state: { page: 1 },
  //       onStateChange: vi.fn(),
  //       renderFallbackValue: 'No data',
  //       mergeOptions: vi.fn(),
  //     }
  //     const options = {
  //       state: { pageSize: 10 },
  //       onStateChange: vi.fn(),
  //       renderFallbackValue: 'No data available',
  //     }
  //     const expectedOptions = {
  //       state: { page: 1, pageSize: 10 },
  //       onStateChange: expect.any(Function),
  //       renderFallbackValue: 'No data available',
  //       mergeOptions: expect.any(Function),
  //     }
  //     const table = useVueTable(options)

  //     // assert that the table is created with merged options
  //     expect(table).toBeDefined()
  //     expect(table.options).toEqual(expectedOptions)
  //   })

  //   // Tests that the function sets the state of the table with provided state
  //   it('should set the state of the table with provided state', () => {
  //     // use fakerjs to mock data
  //     const options = {
  //       state: { page: 1 },
  //     }
  //     const table = useVueTable(options)

  //     // assert that the table state is set with provided state
  //     expect(table).toBeDefined()
  //     expect(table.state).toEqual(options.state)
  //   })

  //   // Tests that the function sets the onStateChange of the table with provided onStateChange
  //   it('should set the onStateChange of the table with provided onStateChange', () => {
  //     // use fakerjs to mock data
  //     const options = {
  //       onStateChange: vi.fn(),
  //     }
  //     const table = useVueTable(options)

  //     // assert that the table onStateChange is set with provided onStateChange
  //     expect(table).toBeDefined()
  //     expect(table.options.onStateChange).toEqual(options.onStateChange)
  //   })

  //   // Tests that the function throws an error when options is undefined
  //   it('should throw an error when options is undefined', () => {
  //     // use fakerjs to mock data
  //     const options = undefined

  //     // assert that the function throws an error when options is undefined
  //     expect(() => {
  //       useVueTable(options)
  //     }).toThrowError('Options is required')
  //   })

  //   // Tests that the function throws an error when mergeOptions is undefined
  //   it('should throw an error when mergeOptions is undefined', () => {
  //     // use fakerjs to mock data
  //     const options = {
  //       mergeOptions: undefined,
  //     }

  //     // assert that the function throws an error when mergeOptions is undefined
  //     expect(() => {
  //       useVueTable(options)
  //     }).toThrowError('mergeOptions is required')
  //   })

  //   // Tests that the function throws an error when mergeOptions returns undefined
  //   it('should throw an error when mergeOptions returns undefined', () => {
  //     // use fakerjs to mock data
  //     const options = {
  //       mergeOptions: () => undefined,
  //     }

  //     // assert that the function throws an error when mergeOptions returns undefined
  //     expect(() => {
  //       useVueTable(options)
  //     }).toThrowError('Merged options cannot be undefined')
  //   })

  //   // Tests that the function throws an error when mergeOptions returns an object without a state property
  //   it('should throw an error when mergeOptions returns an object without a state property', () => {
  //     // use fakerjs to mock data
  //     const options = {
  //       mergeOptions: () => ({}),
  //     }

  //     // assert that the function throws an error when mergeOptions returns an object without a state property
  //     expect(() => {
  //       useVueTable(options)
  //     }).toThrowError('Merged options must have a state property')
  //   })

  //   // Tests that the function throws an error when mergeOptions returns an object with an invalid state property
  //   it('should throw an error when mergeOptions returns an object with an invalid state property', () => {
  //     // use fakerjs to mock data
  //     const options = {
  //       mergeOptions: () => ({ state: 'invalid' }),
  //     }

  //     // assert that the function throws an error when mergeOptions returns an object with an invalid state property
  //     expect(() => {
  //       useVueTable(options)
  //     }).toThrowError('Merged options state must be an object')
  //   })

  //   // Tests that the function throws an error when onStateChange is not a function
  //   it('should throw an error when onStateChange is not a function', () => {
  //     // use fakerjs to mock data
  //     const options = {
  //       onStateChange: 'invalid',
  //     }

  //     // assert that the function throws an error when onStateChange is not a function
  //     expect(() => {
  //       useVueTable(options)
  //     }).toThrowError('onStateChange must be a function')
  //   })

  //   // Tests that the function throws an error when setOptions is not a function
  //   it('should throw an error when setOptions is not a function', () => {
  //     // use fakerjs to mock data
  //     const options = {
  //       mergeOptions: () => ({}),
  //       setOptions: 'invalid',
  //     }

  //     // assert that the function throws an error when setOptions is not a function
  //     expect(() => {
  //       useVueTable(options)
  //     }).toThrowError('setOptions must be a function')
  //   })
})
